# Source: https://hub.docker.com/_/wordpress
version: '3.1'

services:
  wordpress:
    image: wordpress:5.9.1-apache
    restart: always
    ports:
      - 8082:80
    depends_on:
      - "db"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_DEBUG: true
    volumes:
      # - ./wordpress:/var/www/html
      - ./plugins/onstage:/var/www/html/wp-content/plugins/onstage/
      - ./themes/onstage:/var/www/html/wp-content/themes/onstage/
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: