FROM wordpress:5.9.1-apache

RUN [ "apt", "update" ]
RUN [ "apt", "install", "vim" ]

# Evt. warning van Apache over 'could not reliably determine hostname' oplossen: https://stackoverflow.com/questions/66396139/docker-compose-apache2-could-not-reliably-determine-the-servers-fully-qualifi?rq=1